name: Check cache 
description: Check is cache exists
inputs:
  profile:
    description: conan-profile
    required: true
    default: default

outputs:
  exists:  
    value: ${{steps.check-cache.outputs.cache-hit}}

runs:
  using: composite
  steps:
      - name: Set conan storage path
        if: runner.os != 'Windows'
        shell: bash
        run: |
          echo "CONAN_STORAGE=$HOME/.conan2/p" >> $GITHUB_ENV

      - name: Set conan storage path
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          echo "CONAN_STORAGE=$HOME\.conan2/p" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Cache conan packages
        id: check-cache
        uses: actions/cache@v4
        with:
          path: ${{env.CONAN_STORAGE}}
          key: ${{inputs.profile}}
          lookup-only: true

