name: Enable Conan
description: Setup conan with dependecies and cache it
inputs:
  profile:
    description: conan-profile
    required: true
    default: default
  args:
    description: conan build apponly option
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Set storage path
      shell: bash
      run: echo "CONAN_STORAGE=$(conan config home)/p" >> $GITHUB_ENV

    - name: Cache conan packages
      id: cache
      uses: actions/cache@v4
      with:
        path: ${{env.CONAN_STORAGE}}
        key: ${{inputs.profile}}

    - if: ${{steps.cache.outputs.cache-hit != 'true'}}
      name: Conan install
      shell: bash
      run: | 
        conan config install CI/conan
        conan install . --build=missing --profile:build=${{inputs.profile}} --profile:host=${{inputs.profile}} --output-folder=. ${{inputs.args}}
        conan cache clean "*" --source --build --temp --download
