name: Enable Conan
description: Setup conan with dependecies and cache it
inputs:
  profile:
    description: conan-profile
    required: true
    default: default
  args:
    description: conan build apponly option
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Conan defaiult profile detect
      shell: bash
      run: conan profile detect --force

    - name: Conan profiles install
      shell: bash
      run: conan config install CI/conan

    - name: Conan lock create
      shell: bash
      run: conan lock create . --profile:build=${{inputs.profile}} --profile:host=${{inputs.profile}} --lockfile-out=conan.lock
      
    - name: Conan cache download
      id: cache
      uses: actions/cache/restore@v6
      with:
        path: |
          conan-cache-${{inputs.profile}}.tzst
          conan-${{inputs.profile}}.lock
        key: ${{inputs.profile}}

    - name: Check cache hit
      id: cache-hit
      shell: bash
      run: |
        if [ -f "conan-cache-${{inputs.profile}}.tzst" ]; then
          echo "cache_exists=true" >> $GITHUB_OUTPUT
        else
          echo "cache_exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Conan cache restore
      if: steps.cache-hit.outputs.cache_exists == 'true'
      shell: bash
      run: conan cache restore conan-cache-${{inputs.profile}}.tzst

    - name: Check cache is out of date
      if: steps.cache-hit.outputs.cache_exists == 'true'
      id: cache-out-of-date
      shell: bash
      run: |
        if  [ -f "conan-${{inputs.profile}}.lock" ] && cmp -s conan.lock conan-${{inputs.profile}}.lock; then
          echo "cache_out_of_date=false" >> $GITHUB_OUTPUT
        else
          echo "cache_out_of_date=true" >> $GITHUB_OUTPUT
        fi
    
    - name: Conan cache create
      if: steps.cache-hit.outputs.cache_exists == 'false' || steps.cache-out-of-date.outputs.cache_out_of_date == 'true'
      uses: ./.github/actions/conan_cache_create
      with:
        profile: ${{inputs.profile}}
        args: ${{inputs.args}}

      
