name: Ubuntu env
description: Install dev packages for compilation
runs:
  using: composite
  steps:
      - name: Setup environment
        shell: bash
        run: | 
            sudo apt-get update
            sudo apt-get install -y libgl-dev \
                    libgl-dev \
                    libgl1-mesa-dev \
                    libx11-dev \
                    libx11-xcb-dev \
                    libfontenc-dev \
                    libice-dev \
                    libsm-dev \
                    libxau-dev \
                    libxaw7-dev \
                    libx11-xcb-dev \
                    libfontenc-dev \
                    libxcomposite-dev \
                    libxcursor-dev \
                    libxdamage-dev \
                    libxfixes-dev \
                    libxi-dev \
                    libxinerama-dev \
                    libxmu-dev \
                    libxmuu-dev \
                    libxpm-dev \
                    libxrandr-dev \
                    libxres-dev \
                    libxss-dev \
                    libxtst-dev \
                    libxv-dev \
                    libxxf86vm-dev \
                    libxcb-glx0-dev \
                    libxcb-render-util0-dev \
                    libxcb-xkb-dev \
                    libxcb-icccm4-dev \
                    libxcb-image0-dev \
                    libxcb-keysyms1-dev \
                    libxcb-randr0-dev \
                    libxcb-shape0-dev \
                    libxcb-sync-dev \
                    libxcb-xfixes0-dev \
                    libxcb-xinerama0-dev \
                    libxcb-dri3-dev \
                    libxcb-cursor-dev \
                    libxcb-dri2-0-dev \
                    libxcb-dri3-dev \
                    libxcb-present-dev \
                    libxcb-composite0-dev \
                    libxcb-ewmh-dev \
                    libxcb-res0-dev \
                    libxv-dev \
                    libxcb-util-dev \
                    libxcb-util0-dev