if(CONAN_BUILD)
    if(APPLE)
        set_target_properties(${TARGET} PROPERTIES INSTALL_RPATH "@loader_path")
    elseif(UNIX)
        set_target_properties(${TARGET} PROPERTIES INSTALL_RPATH "$ORIGIN")
    endif()
endif()
