if(CONAN_BUILD)
    if(APPLE)
        set_target_properties(${TARGET} PROPERTIES INSTALL_NAME_DIR "@loader_path/${PROJECT_NAME}")
    elseif(UNIX)
        set_target_properties(${TARGET} PROPERTIES INSTALL_RPATH "$ORIGIN/${PROJECT_NAME}")
    endif()
endif()
