if(CONAN_BUILD)
    get_target_property(target_type ${TARGET} TYPE)
    if (target_type STREQUAL "EXECUTABLE")
        if(APPLE)
            set(CMAKE_INSTALL_RPATH "@executable_path/../${CMAKE_INSTALL_LIBDIR}/;@executable_path/../${CMAKE_INSTALL_LIBDIR}/${PROJECT_NAME}")
        elseif(UNIX)
            set(CMAKE_INSTALL_RPATH "$ORIGIN/../${CMAKE_INSTALL_LIBDIR}/${PROJECT_NAME};$ORIGIN/../${CMAKE_INSTALL_LIBDIR};")
        endif()
    elseif(BUILD_SHARED_LIBS)
        if(APPLE)
            set(CMAKE_INSTALL_RPATH "@executable_path/${PROJECT_NAME}")
        elseif(UNIX)
            set(CMAKE_INSTALL_RPATH "$ORIGIN/${PROJECT_NAME};")
        endif()
    endif ()
endif()
