name: Enable Python
description: Install python with requirenments and cache it

runs:
  using: composite
  steps:
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: 3.13

    - name: Cache dependencies
      id: cache
      uses: actions/cache@v4
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}
        restore-keys:
          ${{ env.pythonLocation }}

    - if: ${{steps.cache.outputs.cache-hit != 'true'}}
      name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt