name: Setup Pyhthon MacOS 
description: Install python deps for MacOS
runs:
  using: composite
  steps:
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: pip

      - run: pip install -r requirements.txt
        shell: bash
