name: Setup Pyhthon MacOS 
description: Install python deps for MacOS
runs:
  using: composite
  steps:
      - name: Set up Python 3.14
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
          cache: pip

      - run: pip install -r requirements.txt
        shell: bash
