name: Build project
on: 
  workflow_call:
    inputs:
      deploy:
        description: 'need deploy'
        required: true
        type: boolean  
      attestation:
        description: 'need attestation'
        required: true
        type: boolean

jobs:
  linux-x64-build:
    runs-on: ubuntu-26.04
    permissions:
      id-token: write
      contents: read
      checks: write
      attestations: write
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup_ubuntu_env
      - uses: ./.github/actions/enable_python
      - uses: ./.github/actions/conan_build
        with:
          profile: linux-gcc15_x64

      - uses: ./.github/actions/tests
        with:
          testdir: build/Release
          name: linux-gcc15_x64 tests

      - uses: ./.github/actions/deploy
        if: inputs.deploy
        with:
          builddir: build/Release
          artifact: linux-gcc15_x64
          attestation: ${{inputs.attestation}}

  macos-arm-build:
    runs-on: macos-26
    permissions:
      id-token: write
      contents: read
      checks: write
      attestations: write
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - uses: ./.github/actions/enable_python_macos
      - uses: ./.github/actions/conan_build
        with:
          profile: macos-clang17_arm

      - uses: ./.github/actions/tests
        with:
          testdir: build/Release
          name: macos-clang17_arm tests

      - uses: ./.github/actions/deploy
        if: inputs.deploy
        with:
          builddir: build/Release
          artifact: macos-clang17_arm
          attestation: ${{inputs.attestation}}

  win-x64-build:
    runs-on: windows-2025-vs2026
    permissions:
      id-token: write
      contents: read
      checks: write
      attestations: write
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - uses: ./.github/actions/enable_python
      - uses: ./.github/actions/conan_build
        with:
          profile: win-msvc195_x64
      
      - uses: ./.github/actions/tests
        with:
          testdir: build
          name: win-msvc195_x64 tests
   
      - uses: ./.github/actions/deploy
        if: inputs.deploy
        with:
          builddir: build
          artifact: win-msvc195_x64
          attestation: ${{inputs.attestation}}
