name: Build project
on: 
  workflow_call:
    inputs:
      deploy:
        description: 'need deploy'
        required: true
        type: boolean  
      attestation:
        description: 'need attestation'
        required: true
        type: boolean

jobs:
  cache:
    uses: ./.github/workflows/make_cache.yaml

  linux-x64-build:
    runs-on: ubuntu-22.04
    needs: [cache]
    permissions:
      id-token: write
      contents: read
      checks: write
      attestations: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup_ubuntu_env
      - uses: ./.github/actions/enable_python
      - uses: ./.github/actions/conan_build
        with:
          profile: linux-gcc12_x64

      - uses: ./.github/actions/tests
        with:
          testdir: build/Release
          name: linux-gcc12_x64 tests

      - uses: ./.github/actions/deploy
        if: inputs.deploy
        with:
          builddir: build/Release
          artifact: linux-gcc12_x64
          attestation: ${{inputs.attestation}}

  macos-arm-build:
    runs-on: macos-14
    needs: [cache]
    permissions:
      id-token: write
      contents: read
      checks: write
      attestations: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/enable_python_macos
      - uses: ./.github/actions/conan_build
        with:
          profile: macos-clang15_arm

      - uses: ./.github/actions/tests
        with:
          testdir: build/Release
          name: macos-clang15_arm tests

      - uses: ./.github/actions/deploy
        if: inputs.deploy
        with:
          builddir: build/Release
          artifact: macos-clang15_arm
          attestation: ${{inputs.attestation}}

  macos-x64-build:
    runs-on: macos-13
    needs: [cache]
    permissions:
      id-token: write
      contents: read
      checks: write
      attestations: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: ./.github/actions/enable_python_macos
      - uses: ./.github/actions/conan_build
        with:
          profile: macos-clang15_x64

      - uses: ./.github/actions/tests
        with:
          testdir: build/Release
          name: macos-clang15_x64 tests
    
      - uses: ./.github/actions/deploy
        if: inputs.deploy
        with:
          builddir: build/Release
          artifact: macos-clang15_x64
          attestation: ${{inputs.attestation}}

  win-x64-build:
    runs-on: windows-2022
    needs: [cache]
    permissions:
      id-token: write
      contents: read
      checks: write
      attestations: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/enable_python
      - uses: ./.github/actions/conan_build
        with:
          profile: win-msvc194_x64
      
      - uses: ./.github/actions/tests
        with:
          testdir: build
          name: win-msvc194_x64 tests
   
      - uses: ./.github/actions/deploy
        if: inputs.deploy
        with:
          builddir: build
          artifact: win-msvc194_x64
          attestation: ${{inputs.attestation}}
