name: Build project
on: 
  workflow_call:
    inputs:
      linux_x64_profile:
        description: profile for linux x64
        required: true
        default: linux-gcc12_x64
        type: string

      win_x64_profile:
        description: profile for win x64
        required: true
        default: win-msvc194_x64
        type: string

      macos_arm_profile:
        description: profile for macos arm
        required: true
        default: macos-clang15_arm
        type: string

      macos_x64_profile:
        description: profile for macos x64
        required: true
        default: macos-clang15_x64
        type: string

      sign:
        description: test or release sign
        type: string
        required: true
        default: none
  
jobs:
  cache:
    uses: ./.github/workflows/make_cache.yaml
    with:
      linux_x64_profile: ${{inputs.linux_x64_profile}}
      win_x64_profile: ${{inputs.win_x64_profile}}
      macos_arm_profile: ${{inputs.macos_arm_profile}}
      macos_x64_profile: ${{inputs.macos_x64_profile}}

  linux-x64-build:
    runs-on: ubuntu-22.04
    needs: [cache]
    permissions:
      id-token: write
      contents: read
      checks: write
      attestations: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup_ubuntu_env
      - uses: ./.github/actions/enable_python
      - uses: ./.github/actions/conan_build
        with:
          profile: ${{inputs.linux_x64_profile}}

      - uses: ./.github/actions/tests
        with:
          testdir: build/Release
          name: ${{inputs.linux_x64_profile}} tests

      - uses: ./.github/actions/deploy
        if: inputs.sign != 'none'
        with:
          builddir: build/Release
          artifact: ${{inputs.linux_x64_profile}}
          attestation: ${{inputs.sign != ''}}

  macos-arm-build:
    runs-on: macos-14
    needs: [cache]
    permissions:
      id-token: write
      contents: read
      checks: write
      attestations: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/enable_python_macos
      - uses: ./.github/actions/conan_build
        with:
          profile: ${{inputs.macos_arm_profile}}

      - uses: ./.github/actions/tests
        with:
          testdir: build/Release
          name: ${{inputs.macos_arm_profile}} tests

      - uses: ./.github/actions/deploy
        if: inputs.sign != 'none'
        with:
          builddir: build/Release
          artifact: ${{inputs.macos_arm_profile}}
          attestation: ${{inputs.sign != ''}}

  macos-x64-build:
    runs-on: macos-13
    needs: [cache]
    permissions:
      id-token: write
      contents: read
      checks: write
      attestations: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: ./.github/actions/enable_python_macos
      - uses: ./.github/actions/conan_build
        with:
          profile: ${{inputs.macos_x64_profile}}

      - uses: ./.github/actions/tests
        with:
          testdir: build/Release
          name: ${{inputs.macos_x64_profile}} tests
    
      - uses: ./.github/actions/deploy
        if: inputs.sign != 'none'
        with:
          builddir: build/Release
          artifact: ${{inputs.macos_x64_profile}}
          attestation: ${{inputs.sign != ''}}

  win-x64-build:
    runs-on: windows-2022
    needs: [cache]
    permissions:
      id-token: write
      contents: read
      checks: write
      attestations: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/enable_python
      - uses: ./.github/actions/conan_build
        with:
          profile: ${{inputs.win_x64_profile}}
      
      - uses: ./.github/actions/tests
        with:
          testdir: build
          name: ${{inputs.win_x64_profile}} tests
   
      - uses: ./.github/actions/deploy_with_sign
        if: inputs.sign != 'none'
        with:
          builddir: build
          artifact: ${{inputs.win_x64_profile}}
          sign: ${{inputs.sign}}
          signeddir: build/signed
          token: ${{secrets.SIGNPATH_API_TOKEN}}