name: Build project
on: 
  workflow_call:
    inputs:
      deploy:
        description: 'need deploy'
        required: true
        type: boolean  
      attestation:
        description: 'need attestation'
        required: true
        type: boolean

jobs:
  cache:
    uses: ./.github/workflows/make_cache.yaml

  linux-x64-build:
    runs-on: ubuntu-22.04
    needs: [cache]
    permissions:
      id-token: write
      contents: read
      checks: write
      attestations: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup_ubuntu_env
      - uses: ./.github/actions/enable_python
      - uses: ./.github/actions/conan_build
        with:
          profile: ${{ vars.LINUX_X64_PROFILE }}

      - uses: ./.github/actions/tests
        with:
          testdir: build/Release
          name: ${{ vars.LINUX_X64_PROFILE }} tests

      - uses: ./.github/actions/deploy
        if: inputs.deploy
        with:
          builddir: build/Release
          artifact: ${{ vars.LINUX_X64_PROFILE }}
          attestation: ${{inputs.attestation}}

  macos-arm-build:
    runs-on: macos-14
    needs: [cache]
    permissions:
      id-token: write
      contents: read
      checks: write
      attestations: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/enable_python_macos
      - uses: ./.github/actions/conan_build
        with:
          profile: ${{vars.MACOS_ARM_PROFILE}}

      - uses: ./.github/actions/tests
        with:
          testdir: build/Release
          name: ${{vars.MACOS_ARM_PROFILE}} tests

      - uses: ./.github/actions/deploy
        if: inputs.deploy
        with:
          builddir: build/Release
          artifact: ${{vars.MACOS_ARM_PROFILE}}
          attestation: ${{inputs.attestation}}

  macos-x64-build:
    runs-on: macos-13
    needs: [cache]
    permissions:
      id-token: write
      contents: read
      checks: write
      attestations: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: ./.github/actions/enable_python_macos
      - uses: ./.github/actions/conan_build
        with:
          profile: ${{vars.MACOS_X64_PROFILE}}

      - uses: ./.github/actions/tests
        with:
          testdir: build/Release
          name: ${{vars.MACOS_X64_PROFILE}} tests
    
      - uses: ./.github/actions/deploy
        with:
          builddir: build/Release
          artifact: ${{vars.MACOS_X64_PROFILE}}
          attestation: ${{inputs.attestation}}

  win-x64-build:
    runs-on: windows-2022
    needs: [cache]
    permissions:
      id-token: write
      contents: read
      checks: write
      attestations: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/enable_python
      - uses: ./.github/actions/conan_build
        with:
          profile: ${{vars.WIN_X64_PROFILE}}
      
      - uses: ./.github/actions/tests
        with:
          testdir: build
          name: ${{vars.WIN_X64_PROFILE}} tests
   
      - uses: ./.github/actions/deploy
        if: inputs.deploy
        with:
          builddir: build
          artifact: ${{vars.WIN_X64_PROFILE}}
          attestation: ${{inputs.attestation}}
