name: Check cache deps
on: 
  workflow_call:
    outputs:
        linux_x64_hit:
            value: ${{jobs.linux-x64-check-cache.outputs.exists}}
        macos_arm_hit:
            value: ${{jobs.macos-arm-check-cache.outputs.exists}}
        macos_x64_hit:
            value: ${{jobs.macos-x64-check-cache.outputs.exists}}
        win_x64_hit:
            value: ${{jobs.win-x64-check-cache.outputs.exists}}

jobs:
  linux-x64-check-cache:
    runs-on: ubuntu-22.04
    outputs:
        exists: ${{steps.check-cache.outputs.exists}}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/check_cache
        id: check-cache
        with:
            profile:  ${{ vars.LINUX_X64_PROFILE }}

  macos-arm-check-cache:
    runs-on: macos-14
    outputs:
        exists: ${{steps.check-cache.outputs.exists}}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/check_cache
        id: check-cache
        with:
            profile: ${{ vars.MACOS_ARM_PROFILE }}

  macos-x64-check-cache:
    runs-on: macos-13
    outputs:
        exists: ${{steps.check-cache.outputs.exists}}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/check_cache
        id: check-cache
        with:
            profile: ${{ vars.MACOS_X64_PROFILE }}
          
  win-x64-check-cache:
    runs-on: windows-2022
    outputs:
        exists: ${{steps.check-cache.outputs.exists}}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/check_cache
        id: check-cache
        with:
            profile: ${{ vars.WIN_X64_PROFILE }}
