name: Make cache deps
on: 
  workflow_call:   

jobs:
  check-cache:
    uses: ./.github/workflows/check_cache.yaml
    
  linux-x64-make-cache:
    runs-on: ubuntu-22.04
    needs: [check-cache]
    if: ${{ needs.check-cache.outputs.linux_x64_hit == false }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup_ubuntu_env
      - uses: ./.github/actions/enable_python
      - uses: ./.github/actions/enable_conan
        with:
          profile: ${{vars.LINUX_X64_PROFILE}}

  macos-arm-make-cache:
    runs-on: macos-14
    needs: [check-cache]
    if: ${{ needs.check-cache.outputs.macos_arm_hit == false }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/enable_python_macos
      - uses: ./.github/actions/enable_conan
        with:
          profile: ${{vars.MACOS_ARM_PROFILE}}

  macos-x64-make-cache:
    runs-on: macos-13
    needs: [check-cache]
    if: ${{ needs.check-cache.outputs.macos_x64_hit == false }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/enable_python_macos
      - uses: ./.github/actions/enable_conan
        with:
          profile: ${{vars.MACOS_X64_PROFILE}}
          
  win-x64-make-cache:
    runs-on: windows-2022
    needs: [check-cache]
    if: ${{ needs.check-cache.outputs.win_x64_hit == false }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/enable_python
      - uses: ./.github/actions/enable_conan
        with:
          profile: ${{vars.WIN_X64_PROFILE}}
