name: Develop build
on:
  push:
    tags-ignore:
      - '**'
    branches:
      - master
      - develop

jobs:
  build:
    if: github.event_name != 'pull_request'
    uses: ./.github/workflows/build.yaml
    with:
      deploy: false
      attestation: false
    secrets: inherit
    