name: Release build
on:
    push:
        tags:
            - v*
            
jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      deploy: true
      attestation: true
    secrets: inherit
