name: Release build
on:
    push:
        tags:
            - v*

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      linux_x64_profile: linux-gcc12_x64
      win_x64_profile: win-msvc194_x64
      macos_arm_profile: macos-clang15_arm
      macos_x64_profile: macos-clang15_x64
      sign: release-signing
    secrets: inherit
